-- MySQL Script generated by MySQL Workbench
-- Sun Aug 28 22:07:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HospitalizacionEnCasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HospitalizacionEnCasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HospitalizacionEnCasa` DEFAULT CHARACTER SET utf8 ;
USE `HospitalizacionEnCasa` ;

-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`Persona` (
  `Id` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`Medico` (
  `Especialidad` VARCHAR(30) NOT NULL,
  `Persona_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Persona_Id`),
  CONSTRAINT `fk_Medico_Persona1`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`Familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`Familiar` (
  `Parentesco` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Persona_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Persona_Id`),
  CONSTRAINT `fk_Familiar_Persona1`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`Paciente` (
  `Direccion` VARCHAR(50) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Latitud` DOUBLE NULL,
  `Longitud` DOUBLE NULL,
  `Persona_Id` VARCHAR(20) NOT NULL,
  `Medico_Persona_Id` VARCHAR(20) NOT NULL,
  `Familiar_Persona_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Persona_Id`, `Familiar_Persona_Id`),
  INDEX `fk_Paciente_Medico1_idx` (`Medico_Persona_Id` ASC) VISIBLE,
  INDEX `fk_Paciente_Familiar1_idx` (`Familiar_Persona_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Persona`
    FOREIGN KEY (`Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Medico1`
    FOREIGN KEY (`Medico_Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Medico` (`Persona_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Familiar1`
    FOREIGN KEY (`Familiar_Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Familiar` (`Persona_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`Diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`Diagnostico` (
  `Id` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Sugerencia` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Medico_Persona_Id` VARCHAR(20) NOT NULL,
  `Paciente_Persona_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Diagnostico_Medico1_idx` (`Medico_Persona_Id` ASC) VISIBLE,
  INDEX `fk_Diagnostico_Paciente1_idx` (`Paciente_Persona_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnostico_Medico1`
    FOREIGN KEY (`Medico_Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Medico` (`Persona_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnostico_Paciente1`
    FOREIGN KEY (`Paciente_Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Paciente` (`Persona_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HospitalizacionEnCasa`.`SignosVitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HospitalizacionEnCasa`.`SignosVitales` (
  `Id` INT NOT NULL,
  `Oximetria` DOUBLE NULL,
  `FrecuenciaRespiratoria` DOUBLE NULL,
  `FrecuenciaCardiaca` DOUBLE NULL,
  `Temperatura` DOUBLE NULL,
  `PresionArterial` DOUBLE NULL,
  `Glicemias` DOUBLE NULL,
  `Fecha` DATETIME NOT NULL,
  `Paciente_Persona_Id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_SignosVitales_Paciente1_idx` (`Paciente_Persona_Id` ASC) VISIBLE,
  CONSTRAINT `fk_SignosVitales_Paciente1`
    FOREIGN KEY (`Paciente_Persona_Id`)
    REFERENCES `HospitalizacionEnCasa`.`Paciente` (`Persona_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
