# Generated by Django 3.2.4 on 2022-09-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('Clave', models.CharField(max_length=45)),
                ('Rol', models.CharField(choices=[('1', 'Paciente'), ('2', 'Médico'), ('3', 'Familiar'), ('4', 'Auxiliar'), ('5', 'Enfermera/o')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('Codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('Codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('Parentesco', models.CharField(max_length=45)),
                ('Correo', models.CharField(max_length=45)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Especialidad', models.CharField(max_length=45)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('Registro', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Direccion', models.CharField(max_length=45)),
                ('Ciudad', models.CharField(max_length=45)),
                ('Fecha_nacimiento', models.DateField()),
                ('Latitud', models.CharField(blank=True, max_length=45, null=True)),
                ('Longitud', models.CharField(blank=True, max_length=45, null=True)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('FamiliarId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.familiar')),
                ('MedicoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medico')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('RegistroId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Oximetria', models.FloatField(blank=True, null=True)),
                ('FrecuenciaRespiratoria', models.FloatField(blank=True, null=True)),
                ('FrecuenciaCardiaca', models.FloatField(blank=True, null=True)),
                ('Temperatura', models.FloatField(blank=True, null=True)),
                ('PresionArterial', models.FloatField(blank=True, null=True)),
                ('Glicemia', models.FloatField(blank=True, null=True)),
                ('Fecha', models.DateField()),
                ('PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('DiagnosticoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Sugerencia', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.paciente')),
            ],
        ),
    ]
