# Generated by Django 3.2.4 on 2022-09-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=15, verbose_name='Identificacion')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.FloatField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=45, verbose_name='Email')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Genero')),
                ('rol', models.CharField(choices=[('1', 'Paciente'), ('2', 'Médico'), ('3', 'Familiar'), ('4', 'Auxiliar'), ('5', 'Enfermera/o')], max_length=1, verbose_name='Rol')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('parentesco', models.CharField(max_length=45, verbose_name='Parentesco')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('especialidad', models.CharField(max_length=45, verbose_name='Especialidad')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('registro', models.CharField(max_length=45, verbose_name='Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=45, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
                ('latitud', models.CharField(blank=True, max_length=45, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(blank=True, max_length=45, null=True, verbose_name='Longitud')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Aplicacion.persona')),
                ('familiarId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.familiar')),
                ('medicoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medico')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('registroId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('oximetria', models.FloatField(blank=True, null=True, verbose_name='Oximetría')),
                ('frecuenciaRespiratoria', models.FloatField(blank=True, null=True, verbose_name='Frecuencia respiratoria')),
                ('frecuenciaCardiaca', models.FloatField(blank=True, null=True, verbose_name='Frecuencia cardiaca')),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
                ('presionArterial', models.FloatField(blank=True, null=True, verbose_name='Presion arterial')),
                ('glicemia', models.FloatField(blank=True, null=True, verbose_name='Glicemia')),
                ('fecha', models.DateField()),
                ('pacienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('diagnosticoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
                ('sugerencia', models.CharField(max_length=45, verbose_name='Sugerencia')),
                ('Fecha', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to='Aplicacion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='Aplicacion.paciente')),
            ],
        ),
    ]
