# Generated by Django 3.2.4 on 2022-09-29 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='familiarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medico'),
        ),
    ]
