# Generated by Django 3.0.7 on 2022-09-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('Clave', models.CharField(max_length=45)),
                ('Rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hospital.Persona')),
                ('Codigo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('Parentesco', models.CharField(max_length=45)),
                ('Correo', models.CharField(max_length=45)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hospital.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('Especialidad', models.CharField(max_length=45)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hospital.Persona')),
                ('Registro', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Direccion', models.CharField(max_length=45)),
                ('Ciudad', models.CharField(max_length=45)),
                ('Fecha_nacimiento', models.DateField()),
                ('Latitud', models.CharField(max_length=45, null=True)),
                ('Longitud', models.CharField(max_length=45, null=True)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hospital.Persona')),
                ('FamiliarId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Familiar')),
                ('MedicoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('RegistroId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Oximetria', models.FloatField()),
                ('FrecuenciaRespiratoria', models.FloatField()),
                ('FrecuenciaCardiaca', models.FloatField()),
                ('Temperatura', models.FloatField()),
                ('PresionArterial', models.FloatField()),
                ('Glicemia', models.FloatField()),
                ('Fecha', models.DateField()),
                ('PacienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('DiagnosticoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
                ('Sugerencia', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Medico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Paciente')),
            ],
        ),
    ]
