# Generated by Django 3.0.7 on 2022-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Latitud',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Longitud',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='FrecuenciaCardiaca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='FrecuenciaRespiratoria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='Glicemia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='Oximetria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='PresionArterial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='Temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
